<?php
use Smartcore\InPostInternational\Block\Adminhtml\Order\View\InpostOrderView;

/**
 * @var $block InpostOrderView
 */
?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $escaper->escapeHtml(__('InPost International shipments')) ?></span>
    </div>
    <div class="admin__table-wrapper">
        <div class="field">
            <?php if ($shipments = $block->getInpostShipments()): ?>
                <table class="data-table admin__table-primary">
                    <thead class="headings">
                    <tr>
                        <th><?= $escaper->escapeHtml(__('Tracking number')) ?></th>
                        <th><?= $escaper->escapeHtml(__('Service')) ?></th>
                        <th><?= $escaper->escapeHtml(__('Details')) ?></th>
                        <th><?= $escaper->escapeHtml(__('Actions')) ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($shipments as $shipment): ?>
                        <tr>
                            <td>
                                <a href="<?= $escaper->escapeUrl($block->getShippingTrackingUrl($shipment)) ?>">
                                    <?= $escaper->escapeHtml($shipment->getTrackingNumber()) ?>
                                </a>
                            </td>
                            <td>
                                <?= $escaper->escapeHtml($block->getShippingService($shipment)) ?>
                            </td>
                            <td>
                                <div>
                                    <?php $details = $block->getShippingDetails($shipment); ?>
                                    <?php foreach ($details as $key => $value): ?>
                                        <div class="details-<?= $escaper->escapeHtmlAttr($key) ?>">
                                            <?= $escaper->escapeHtml($value) ?>
                                            <?php if ($key == 'target_point'): ?>
                                                <?php $pointName = explode(" ", $value); ?>
                                                <a data-inpost-select-point="
                                                <?= $escaper->escapeHtmlAttr($pointName[1]) ?>" href="#">
                                                    <?= $escaper->escapeHtml(__('Show on the map')) ?>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            </td>
                            <td>
                                <div class="actions" style="padding: 5px;">
                                    <a class="action-default primary"
                                       href="<?= $escaper->escapeUrl($block->getLabelUrl($shipment)) ?>">
                                        <?= $escaper->escapeHtml(__('Print label')) ?>
                                    </a>
                                </div>
                                <?php if ($block->isReturnPossible($shipment)): ?>
                                    <div class="actions" style="padding: 5px;">
                                        <a class="action-default primary"
                                           href="<?= $escaper->escapeUrl($block->getReturnUrl($shipment)) ?>"
                                            <?php if ($block->isUrlBlank($shipment)): ?> target="_blank" <?php endif; ?>
                                        >
                                            <?= $escaper->escapeHtml(__('Return')) ?>
                                        </a>
                                    </div>
                                <?php endif ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif ?>
            <?php $selectedMethod = $block->getSelectedMethod() ?? '';?>
            <form action="<?= $escaper->escapeUrl($block->getUrl('inpostinternational/shipment/create')) ?>"
                  class="inpost-shipments-form">
                <div class="control" style="float: left;margin-right: 15px">
                    <input type="hidden" name="order_id"
                           value="<?= $escaper->escapeHtmlAttr($block->getOrder()->getId()) ?>">
                    <select id="shipping_method" class="admin__control-select" name="shipping_method" required>
                        <option value=""><?= $escaper->escapeHtml(__('Choose method')) ?></option>
                        <?php foreach ($block->getInpostShippingMethods() as $method): ?>
                            <option value="<?= $escaper->escapeHtmlAttr($method['value']) ?>"
                                <?php if ($selectedMethod == $method['value']): ?> selected<?php endif; ?>>
                                <?= $escaper->escapeHtml($method['label']) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <button id="submit" title="Submit" type="submit" class="action-default scalable edit primary">
                    <span><?= $escaper->escapeHtml(__('Create shipment')) ?></span>
                </button>
            </form>
        </div>
    </div>
</section>
